#!/bin/bash
set -e

# ============================================
#  SubBoard Docker 部署脚本 (1Panel 环境)
#  用法: bash deploy-1panel.sh
# ============================================

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m\033[0m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
err()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

COMPOSE_FILE="docker-compose.1panel.yml"
ENV_FILE=".env.production"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# ---------- 1. 检查 Docker ----------
check_docker() {
    if ! command -v docker &>/dev/null; then
        err "Docker 未安装"
        exit 1
    fi
    if ! docker compose version &>/dev/null; then
        err "Docker Compose 未安装 (需要 V2.000+)"; exit 1
    fi
    ok "Docker 和 Docker Compose 已就安装"
}

# ---------- 2. 生成配置 ----------
generate_config() {
    if [ -f "$ENV_FILE" ]; then
        info "检测到已有 $ENV_FILE 配置文件"
        read -p " "是否使用现有配置？ (y/n) [n]: " use_existing
        if [ "$use_existing" != "y" ] && [ "$use_existing" != "Y" ]; then
            backup_env
            generate_new_config
        else
            info "使用现有配置"
        fi
    else
        generate_new_config
    fi
}

backup_env() {
    local backup="${ENV_FILE}.backup.$(date +%Y%m%d%H%M%S)"
    info "备份现有配置到 $backup"
    cp "$ENV_FILE" "$backup"
}

generate_new_config() {
    echo ""
    echo -e "${CYAN}--- 配置参数 ---${NC}"

    SERVER_IP=$(curl -sf ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    read -p "外部 HTTP 端口 [8080]: " APP_PORT
    APP_PORT=${APP_PORT:-8080}

    read -p "绑定域名 (留空则用 IP 访问): " DOMAIN
    if [ -n "$DOMAIN" ]; then
        SUB_BASE_URL="https://${DOMAIN}"
    else
        SUB_BASE_URL="http://${SERVER_IP}:${APP_PORT}"
        warn "未设置域名， 订阅链接将使用 ${SUB_BASE_URL}"
    fi

    read -p "管理员用户名 [admin]: " ADMIN_USERNAME
    ADMIN_USERNAME=${ADMIN_USERNAME:-admin}

    read -p "管理员密码 [admin]: " ADMIN_PASSWORD
    ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    if [ "$ADMIN_PASSWORD" = "admin" ]; then
        warn "使用默认密码 admin，建议生产环境修改"
    fi

    read -p "允许用户注册 (true/false) [true]: " ALLOW_REGISTER
    ALLOW_REGISTER=${ALLOW_REGISTER:-true}

    read -p "CORS 兺许的域名 (多个用逗号分隔， [留空跳过]: " CORS_ORIGINS
    CORS_ORIGINS=${CORS_ORIGINS:-}

    APP_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)
    INIT_TOKEN=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)

    echo ""
    echo -e "${CYAN}--- 配置摘要 ---${NC}"
    echo "  安装目录:     $REPO_DIR"
    echo "  端口:         $APP_PORT"
    echo "  域名:         ${DOMAIN:-无(用IP)}"
    echo "  订阅URL:     $SUB_BASE_URL"
    echo "  管理员:       $ADMIN_USERNAME / $ADMIN_PASSWORD"
    echo "  允许注册:     $ALLOW_REGISTER"
    echo "  CORS:         ${CORS_ORIGINS:-无}"
    echo -e "${CYAN}------------------${NC}"
    read -p "确认部署? (y/n) [y]: " confirm
    if [ -n "$confirm" ] && [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        err "已取消"; exit 1
    fi
}

# ---------- 3. Write .env ----------
write_env() {
    cat > "$ENV_FILE" <<EOF
# SubBoard Configuration - generated by deploy script
APP_PORT=${APP_PORT}
APP_SECRET=${APP_SECRET}
INIT_TOKEN=${INIT_TOKEN}
SUB_BASE_URL=${SUB_BASE_URL}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ALLOW_REGISTER=${ALLOW_REGISTER}
CORS_ORIGINS=${CORS_ORIGINS}
EOF
    ok "配置文件已写入 $ENV_FILE"
}

# ---------- 4. Build and start ----------
build_and_start() {
    echo ""
    info "构建 Docker 镜像 (首次可能较慢)..."

    docker compose -f docker-compose.1panel.yml build --no-cache 2>&1

    info "启动服务..."
    docker compose -f docker-compose.1panel.yml up -d

    info "等待服务就绪..."
    local retries=0
    while [ $retries -lt 30 ]; do
        if curl -sf "http://localhost:${APP_PORT}/api/health" >/dev/null 2>&1; then
            ok "服务已就绪"
            return
        fi
        retries=$((retries + 1))
        sleep 2
        if [ $((retries % 5)) -eq 0 ]; then
            warn "等待中... ($retries/30)"
        fi
    done

}

# ---------- 5. 输出 1Panel 配置指引 ----------
show_guide() {
    if [ -z "$DOMAIN" ]; then
        PROTO="https"
        [ "$ENABLE_HTTPS" = "n" ] && PROTO="http"
        ACCESS_URL="${PROTO}://${DOMAIN}"
    else
        ACCESS_URL="http://${SERVER_IP}:${APP_PORT}"
    fi

    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}  部署完成!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo -e "  访问地址:    ${CYAN}${ACCESS_URL}${NC}"
    echo -e "  管理后台:    ${CYAN}${ACCESS_URL}/admin${NC}"
    echo -e "  管理员:      ${CYAN}${ADMIN_USERNAME}${NC}"
    echo -e "  密码:        ${CYAN}${ADMIN_PASSWORD}${NC}"
    echo ""
    echo -e "  ${YELLOW}1Panel Nginx 反代配置:${NC}"
    echo "  在 1Panel -> 网站 -> 创建反向代理网站:"
    echo "    代理地址: http://127.0.0.1:${APP_PORT}"
    echo ""
    echo "  ${CYAN}常用命令:${NC}"
    echo "    查看日志:  cd ${REPO_DIR} && docker compose -f docker-compose.1panel.yml logs -f"
    echo "    重启服务:    cd ${REPO_DIR} && docker compose -f docker-compose.1panel.yml restart"
    echo "    勾止服务:    cd ${REPO_DIR} && docker compose -f docker-compose.1panel.yml down"
    echo "    查看状态:  cd ${REPO_DIR} && docker compose -f docker-compose.1panel.yml ps"
    echo "    更新部署:  cd ${REPO_DIR} && git pull && bash deploy-1panel.sh"
    echo ""
    echo -e "${GREEN}============================================${NC}"
}

# ========== 主流程 ==========
check_docker
generate_config
write_env
build_and_start
show_guide
